
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scrum.a2;
import javafx.application.Application;
import javafx.stage.Stage;

public class VendingMachineMain extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception{
        
        new Window(new VendingMachine(), primaryStage);
    }

}
